apiVersion: v1
kind: ConfigMap
metadata:
  name: twinops-config
  namespace: twinops
data:
  # Application Configuration
  API_TITLE: "TwinOps API"
  API_VERSION: "0.1.0"
  ENVIRONMENT: "production"

  # Database URLs (non-sensitive)
  NEO4J_URI: "bolt://neo4j:7687"
  REDIS_URL: "redis://redis:6379/0"
  MONGODB_URL: "mongodb://mongodb:27017/twinops"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"

  # Infrastructure
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  TEMPORAL_NAMESPACE: "twinops"
  TEMPORAL_TASK_QUEUE: "twinops-workflows"
  TEMPORAL_HOST: "temporal:7233"

  # Monitoring
  PROMETHEUS_PUSHGATEWAY: "http://prometheus-pushgateway:9091"
  OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger-collector:14250"
  JAEGER_AGENT_HOST: "jaeger-agent"
  JAEGER_AGENT_PORT: "6831"

  # Performance
  RATE_LIMIT_PER_MINUTE: "60"
  RATE_LIMIT_PER_HOUR: "1000"
  QUERY_TIMEOUT_SECONDS: "30"
  MAX_CONCURRENT_QUERIES: "100"

  # Vector Search
  VECTOR_SEARCH_TOP_K: "20"
  GRAPH_TRAVERSAL_MAX_DEPTH: "3"

  # LLM Configuration
  OPENAI_MODEL: "gpt-4"
  CLAUDE_MODEL: "claude-3-opus-20240229"
  EMBEDDING_MODEL: "text-embedding-ada-002"
  MAX_TOKENS: "4096"
  TEMPERATURE: "0.7"

  # Feature Flags
  ENABLE_SLACK_BOT: "true"
  ENABLE_JIRA_INTEGRATION: "true"
  ENABLE_GITHUB_INTEGRATION: "true"
  ENABLE_GOOGLE_WORKSPACE: "true"
  ENABLE_WORKFLOW_AUTOMATION: "true"
  ENABLE_ADVANCED_GRAPH_RAG: "true"
  ENABLE_AUTO_DELEGATION: "true"
