version: '3.9'
services:
  backend:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.backend
    env_file:
      - ../../.env.example
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
      - redis
      - elasticsearch

  neo4j:
    image: neo4j:5.11
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kafka:
    image: bitnami/kafka:3.6
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  temporal:
    image: temporalio/auto-setup:1.20
    environment:
      - TEMPORAL_SKIP_ADD_CUSTOM_SEARCH_ATTRIBUTES=true
    ports:
      - "7233:7233"

  jaeger:
    image: jaegertracing/all-in-one:1.51
    ports:
      - "16686:16686"
      - "14250:14250"

  prometheus:
    image: prom/prometheus:v2.48.0
    ports:
      - "9090:9090"
