apiVersion: v1
kind: Service
metadata:
  name: twinops-backend
  namespace: twinops
  labels:
    app: twinops
    component: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: twinops
    component: backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

---
apiVersion: v1
kind: Service
metadata:
  name: twinops-backend-internal
  namespace: twinops
  labels:
    app: twinops
    component: backend
spec:
  type: ClusterIP
  selector:
    app: twinops
    component: backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
